version: "3"

tasks:
  dev:
    desc: Uruchamia serwer deweloperski (HMR)
    cmds:
      - deno run -A npm:vinxi dev
    interactive: true

  build:
    desc: Buduje projekt do produkcji
    cmds:
      - deno run -A npm:vinxi build

  start:
    desc: Uruchamia zbudowaną aplikację (wymaga wcześniejszego build)
    cmds:
      - deno run -A npm:vinxi start
    interactive: true

  start-static:
    desc: Uruchamia build bezpośrednio przez Deno (wymaga wcześniejszego build)
    cmds:
      - sh -c 'NODE_ENV=production exec deno run -A .output/server/index.mjs'
    interactive: true

  typecheck:
    desc: Sprawdza typy TypeScript w całym projekcie
    cmds:
      - deno check app.config.ts createApp.ts src/entry-api.ts src/entry-client/entry-client.tsx src/entry-client/App.tsx src/entry-client/appStore.ts

  install:
    desc: Instaluje zależności npm przez Deno
    cmds:
      - deno install
